# Generated by Django 5.0.6 on 2024-05-15 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_adress_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_register',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
