# Generated by Django 5.0.6 on 2024-05-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_article_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='classNames',
        ),
    ]
